# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: PlanckTeam/planckteam.github.io
  branch: main

media_folder: /public/media
public_folder: /public

collections:
  - name: blog
    label: Posts
    label_singular: Post
    folder: /src/content/blog
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Publish Date, name: pubDate, widget: datetime, type: date }
      - { label: Updated Date, name: updatedDate, widget: datetime, type: date }
      - { label: Hero Image, name: heroImage, widget: image, required: false }
      - { label: Body, name: body, widget: richtext }